import Head from "next/head";
import Image from "next/image";
import banner_img from "@/public/banner-home.png";
import estilos from "./Styles/Home.module.css";
import img1 from "@/public/banner-sabores.jpg";
import img2 from "@/public/eventos-image.jpg";
import img3 from "@/public/sobre-image.jpg";

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous"/>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"/>
      </Head>

      <main>
        <div className={estilos.homeBanner}>
          <h1>sorvete artesanal</h1>
          <Image src={banner_img} className={estilos.bannerImage} alt="Imagem de um sorvete" />
        </div>

        <div className={estilos.conteudoHome}>
          <div className={estilos.cardsHome}>
            <div className={`${estilos.cardItem} ${estilos.cardImagem1}`}>
              <Image src={img1} alt="Imagem de sabores de sorvete"/>
            </div>
            <div className={`${estilos.cardItem} ${estilos.cardTexto1}`}>
              <div className={estilos.itemTexto}>
                <h2>Nossos Sabores</h2>
                <span>Novos e deliciosos</span>
                <p>
                  Sorvete bom é aquele feito com os melhores ingredientes! Aqui na gelateria todos os 
                  nossos produtos são naturais, à base de frutas e sem nenhum conservante! Também temos 
                  opções sem lactose e sem açúcar. Venha conhecer e perceber que tem como o sorvete ser 
                  delicioso e saudável ao mesmo tempo!
                </p>
              </div>
            </div>
            <div className={`${estilos.cardItem} ${estilos.cardTexto2}`}>
              <div className={estilos.itemTexto}>
                <h2>Nossos eventos</h2>
                <span>Delícias com sorvete</span>
                <p>
                  Mais do que uma sorveteria, uma extensão da sua casa! Estamos aqui prontinhos para 
                  te atender e oferecer os melhores eventos com os melhores sorvete da sua vida! Venha 
                  nos conhecer e passar um tempo aqui com a gente.
                </p>
              </div>
            </div>
            <div className={`${estilos.cardItem} ${estilos.cardImagem2}`}>
              <Image src={img2} alt="Imagem de eventos"/>
            </div>
            <div className={`${estilos.cardItem} ${estilos.cardImagem3}`}>
              <Image src={img3} alt="Imagem confraternização"/>
            </div>
            <div className={`${estilos.cardItem} ${estilos.cardTexto3}`}>
              <div className={estilos.itemTexto}>
                <h2>Sobre nós</h2>
                <span>Alegria em cada casquinha!</span>
                <p>
                  Venha tomar o melhor sorvete da região aqui com a gente! Nós estamos há anos no 
                  mercado produzindo o que tem de melhor para o nosso cliente e você não pode ficar 
                  fora dessa. Venha nos fazer uma visita e aproveite o melhor atendimento e o melhor 
                  sorvete da cidade.
                </p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
